# Generated by Django 5.0.6 on 2024-06-28 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stockapp.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.user')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
